dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - valgrind

before_install:
  - pip install --user cpp-coveralls

script:
  - ./travis.sh

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" -e gtest/ tests/mediator_unittests.cc
